
#Overworld Ore config for janoeo
[janoeo]
	#Copper ore generation: disable / enable
	copperOreGen = true
	#Tin ore generation: disable / enable
	tinOreGen = true
	#Aluminium ore generation: disable / enable
	aluminiumOreGen = true
	#Uranium ore generation: disable / enable
	uraniumOreGen = true
	#Osmium ore generation: disable / enable
	osmiumOreGen = false
	#Silver ore generation: disable / enable
	silverOreGen = true
	#Lead ore generation: disable / enable
	leadOreGen = true
	#Ruby ore generation: disable / enable
	rubyOreGen = false
	#Sapphire ore generation: disable / enable
	sapphireOreGen = false
	#Amethyst ore generation: disable / enable
	amethystOreGen = false
	#Zinc ore generation: disable / enable
	zincOreGen = true
	#Dense coal ore generation: disable / enable
	denseCoalOreGen = true
	#Dense copper ore generation: disable / enable
	denseCopperOreGen = true
	#Dense diamond ore generation: disable / enable
	denseDiamondOreGen = true
	#Dense emerald ore generation: disable / enable
	denseEmeraldOreGen = true
	#Dense gold ore generation: disable / enable
	denseGoldOreGen = true
	#Dense iron ore generation: disable / enable
	denseIronOreGen = true
	#Dense lapis ore generation: disable / enable
	denseLapisOreGen = true
	#Dense redstone ore generation: disable / enable
	denseRedstoneOreGen = true
	#Dense tin ore generation: disable / enable
	denseTinOreGen = true

